### ISSUE TITLE
Add { passive: false } to allow event.preventDefault()

### ISSUE THREAD

**Issue by blaues0cke** [woutervh-/react-pan-and-zoom-hoc#16]
This kinda relates to https://github.com/woutervh-/react-pan-and-zoom-hoc/issues/12 but I want to leave it here for discussions. As described in this [stackoverflow post](https://stackoverflow.com/a/49853392/301277) and the [documentation of "addEventListener"](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) `touchmove` stopped to be cancelable using `event.preventDefault()` until we register the event listender like this:

    document.addEventListener('touchmove', this.handleMouseMove, {passive: false});

In my opinion its ok the keep this like the current version, but maybe there should be an option to "enable" the `{passive: false}`-flag?

**Comment by woutervh-** [comment]
Hi @blaues0cke 

Thanks for the heads up. I think it's a good idea to add the `passive: false` flag by default since it is the intended behavior of the library. I will make an update and keep you updated.

**Comment by woutervh-** [comment]
Fixed in version `2.1.5`

**Comment by blaues0cke** [comment]
Thank you very much! :-)
