### ISSUE TITLE
Zooming not on center

### ISSUE THREAD

**Issue by JasperDeRoeck** [woutervh-/react-pan-and-zoom-hoc#4]
We have a large svg map component on which we zoom but it zooms more onto the upper left corner instead of where the mouse pointer is supposed to be. Is there an easy way to set the mouse pointer as the center of the zoom or maybe set the zooming onto a fixed point so it always zooms on the center and not based on the mouse position?

**Comment by woutervh-** [comment]
Closing for housekeeping purposes.
