### ISSUE TITLE
Type 'keyof T' does not satisfy the constraint 'string'

### ISSUE THREAD

**Issue by Schlesiger** [woutervh-/react-pan-and-zoom-hoc#5]
Currently when importing `react-pan-and-zoom-hoc`, TypeScript throws an error: `Type 'keyof T' does not satisfy the constraint 'string'`

[Here's a thread on the subject.](https://github.com/Microsoft/TypeScript/issues/25260)

**Comment by woutervh-** [comment]
Thanks @Schlesiger. I will make an update to be compatible with newer TS version.

**Comment by woutervh-** [comment]
Should be fixed with version `1.3.0`. Please re-open or create a new issue if it's still a problem for you.
