### ISSUE TITLE
`1.3.0` breaks zooming

### ISSUE THREAD

**Issue by Schlesiger** [woutervh-/react-pan-and-zoom-hoc#6]
Thanks for the quick update to #5.

After updating to the latest `1.3.0`, zooming is broken for me. I see that there were changes to fix #4, but it was working for me before in my project. [Here is a demo using `1.1.11` with zooming working.](http://wallzero.gitlab.io/jsplumb-react/#/en/simpleDiagram)

[Here is where I implement `react-pan-and-zoom-hoc`.](https://gitlab.com/wallzero/jsplumb-react/blob/master/src/Graph/index.tsx) Do you see where I am going wrong? In my `handlePanAndZoom` callback I've tried changing:

```tsx
const zoomXOffset = prevXoffset + (prevXoffset - xOffset);
const zoomYOffset = prevYOffset + (prevYOffset - yOffset);
```

to:
```tsx
const zoomXOffset = xOffset;
const zoomYOffset = yOffset;
```

**Comment by woutervh-** [comment]
hi @Schlesiger 

Thanks for the report. However nothing should have changed in version `1.3.0` regarding zoom logic. You mentioned that you were on `1.1.11`. There was a change `1.1.12` that changed some of the pan/zoom logic:
https://github.com/woutervh-/react-pan-and-zoom-hoc/commit/25dbf48844540bc1094579e760148a795971ebee?diff=split#diff-ab43f4870721a4f70d3bfd052c4046ebL36

With the new examples file you can see how the x, y, and zoom values change:
https://github.com/woutervh-/react-pan-and-zoom-hoc/blob/master/examples/main.js

**Comment by woutervh-** [comment]
Closing for house keeping.
