### ISSUE TITLE
Disable Zooming on Scroll

### ISSUE THREAD

**Issue by eunicorn** [woutervh-/react-pan-and-zoom-hoc#7]
Is it possible to add an option to disable zooming on scroll? I have a use case that requires both scrolling using the mouse wheel and panning. Thank you very much!

**Comment by woutervh-** [comment]
hi @eunicorn 

Thanks for the suggestion!
Yes, this is possible, I will add a prop to opt out of that functionality. I will update the issue when it's done.

**Comment by woutervh-** [comment]
hi @eunicorn 

I have added the prop `disableScrollZoom`: https://github.com/woutervh-/react-pan-and-zoom-hoc/commit/191ba5341bf6b8e8a1d77d71d8ef012e00a648eb

It's been released in the new version `1.4.0`, let me know if it worked out for you.

**Comment by eunicorn** [comment]
This works perfectly! Thank you!
