### ISSUE TITLE
componentRef.current.addEventListener is not a function in React 16.5

### ISSUE THREAD

**Issue by zrisher** [woutervh-/react-pan-and-zoom-hoc#9]
I receive `TypeError: this.componentRef.current.addEventListener is not a function` when attempting the Unmanaged Example from the Readme while using React 16.5.

The error is thrown from [`panAndZoomHoc.tsx#L75`](https://github.com/woutervh-/react-pan-and-zoom-hoc/blob/master/src/panAndZoomHoc.tsx#L75)
```
if (this.componentRef.current) {
  this.componentRef.current.removeEventListener('wheel', this.handleWheel);
}
```
Using Chrome debugger, it appears `this.componentRef.current` returns the component itself and not a DOM reference:

![image](https://user-images.githubusercontent.com/1958130/55867986-69a18500-5b38-11e9-8190-c63647d65505.png)

Purportedly we're supposed to use [`ReactDOM.findDOMNode(component)`](https://reactjs.org/docs/react-dom.html#finddomnode) to get the DOM reference from a component.

**Comment by woutervh-** [comment]
Hi @zrisher 
Good point, I forgot about wrapped React components.
I will fix it and release a new version, in the meantime version `1.4.1` still uses the old `findDOMNode` method and should work just fine.

Thanks

**Comment by woutervh-** [comment]
I also update the major version `2` so you can also use `2.0.1` now.
Let me know if it works for you.

**Comment by zrisher** [comment]
@woutervh- Thanks for the quick response. You are correct, `1.4.1` works just fine. I don't see `2.0.1` up on NPM but will switch over asap. Thank you!
